CXX = g++
GFLAGS = -std=c++11 -O2 -Wextra -Wall -Werror -Wno-sign-compare -Wno-unused-result -pedantic
FILES = main.cpp 
NAME = solution

cmp:
	$(CXX) $(GFLAGS) $(FILES) -o $(NAME)

clean:
	rm -f *.o $(NAME)